apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-controller
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /board
        backend:
          serviceName: rahulltelkarnginxboard
          servicePort: 80
